name: Visual Studio builds
on:
  push:
  workflow_dispatch:
permissions:
  contents: read
  
jobs:
  MSVC_CI_build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflow
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install dependencies
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          echo '{' > vcpkg.json
          echo '    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",' >> vcpkg.json
          echo '    "name": "np2kai",'  >> vcpkg.json
          echo '    "description": "NP2kai is PC-9801 series emulator",'  >> vcpkg.json
          echo '    "version": "0.86",'  >> vcpkg.json
          $part1 = '    "builtin-baseline": "'
          $part2 = "${{ github.sha }}"
          $part3 = '",'
          echo "$part1$part2$part3" >> vcpkg.json
          echo '    "dependencies": [' >> vcpkg.json
          echo '       {"name": "openssl", "version>=": "3.0.0"},' >> vcpkg.json
          echo '       {"name": "sdl2", "version>=": "2.24.0"},' >> vcpkg.json
          echo '       {"name": "sdl2-mixer", "version>=": "2.6.1"},' >> vcpkg.json
          echo '       {"name": "sdl2-ttf", "version>=": "2.20.0"},' >> vcpkg.json
          echo '       {"name": "libusb", "version>=": "1.0.26"}' >> vcpkg.json
          echo '     ]' >> vcpkg.json
          echo '}' >> vcpkg.json
          cat vcpkg.json
          vcpkg integrate install
      - name: run cmake
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          cmake . -G"Ninja" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_MAKE_PROGRAM=ninja.exe
          dir
          